// ==UserScript==
// @id             mynovelreader@ywzhaiqi@gmail.com
// @name           My Novel Reader
// @name:zh-CN     小说阅读脚本
// @name:zh-TW     小說閱讀腳本
// @version        8.1.0
// @namespace      https://github.com/ywzhaiqi
// @author         ywzhaiqi
// @contributor    Roger Au, shyangs, JixunMoe、akiba9527 及其他网友
// @description    小说阅读脚本，统一阅读样式，内容去广告、修正拼音字、段落整理，自动下一页
// @description:zh-CN  小说阅读脚本，统一阅读样式，内容去广告、修正拼音字、段落整理，自动下一页
// @description:zh-TW  小說閱讀腳本，統一閱讀樣式，內容去廣告、修正拼音字、段落整理，自動下一頁
// @license        GPL version 3
// @grant          GM_xmlhttpRequest
// @grant          GM_addStyle
// @grant          GM_getValue
// @grant          GM_setValue
// @grant          GM_getResourceURL
// @grant          GM_openInTab
// @grant          GM_setClipboard
// @grant          GM_registerMenuCommand
// @grant          GM_info
// @grant          unsafeWindow
// @homepageURL    https://greasyfork.org/scripts/292/
// @require        https://mirrors.sustech.edu.cn/cdnjs/ajax/libs/vue/2.2.6/vue.min.js#sha256=7166598e78fdf6bca707e6fc15a346522bf17359094916bc64cfc4efb703ab42
// @require        https://mirrors.sustech.edu.cn/cdnjs/ajax/libs/jquery/2.1.1/jquery.min.js#sha256=c0d4098bc8b34c6f87a3d7723988ae81214a53a0bb4a1d4d36a67640f98ed079
// @require        https://mirrors.sustech.edu.cn/cdnjs/ajax/libs/underscore.js/1.7.0/underscore-min.js#sha256=7b6fbd8af1c538408f2fe7eef5f6c52b85db12ab91b63277287e5e9ea83a4931
// @require        https://mirrors.sustech.edu.cn/cdnjs/ajax/libs/keymaster/1.6.1/keymaster.min.js#sha256=b5db262c4377030dc22c1ed176f1b8f1a29e557d0fa8afae0d185e5dc57dd3fb
// @require        https://mirrors.sustech.edu.cn/cdnjs/ajax/libs/crypto-js/4.1.1/crypto-js.min.js#sha256=8e3b0117f4df4be452c0b6af5b8f0a0acf9d4ade23d08d55d7e312af22077762

// @connect        *
// @connect        *://*.qidian.com/
// @connect        bgme.bid
// @connect        xrzww.com
// @connect        qidian.com

// @include        *://vipreader.qidian.com/chapter/*/*
// @include        *://www.qdmm.com/BookReader/*,*.aspx
// @include        *://chuangshi.qq.com/read/bookreader/*.html*
// @include        *://chuangshi.qq.com/*bk/*/*-r-*.html*
// @include        *://yunqi.qq.com/*bk/*/*.html
// @include        *://dushu.qq.com/read.html?bid=*
// @include        *://www.jjwxc.net/onebook.php?novelid=*&chapterid=*
// @include        *://my.jjwxc.net/onebook_vip.php?novelid=*&chapterid=*
// @include        *://book.zongheng.com/chapter/*/*.html
// @include        *://www.xxsy.net/chapter/*.html
// @include        *://book.zhulang.com/*/*.html
// @include        *://www.17k.com/chapter/*/*.html
// @include        *://mm.17k.com/chapter/*/*.html
// @include        *://www.xkzw.org/*/*.html
// @include        *://shouda8.com/*/*.html
// @include        *://novel.hongxiu.com/*/*/*.shtml
// @include        *://www.readnovel.com/novel/*.html
// @include        *://shushan.zhangyue.net/book/*/*/
// @include        *://weread.qq.com/web/reader/*
// @match          *://www.qimao.com/shuku/*-*/
// @match          *://www.qidian.com/chapter/*/*
// @match          *://m.qidian.com/chapter/*/*
// @match          *://read.zongheng.com/chapter/*/*.html
// @match          *://www.duread.cn/chapter/book_chapter_detail/*
// @match          *://www.duyuedu.net/chapter/book_chapter_detail/*
// http://www.tianyabook.com/*/*.htm

// @include        *://tieba.baidu.com/p/*
// @include        *://booklink.me/*

// booklink.me
// @include        *://www.dudukan.net/html/*/*/*.html
// @include        *://www.tadu.com/book/*/*/
// @exclude        *://www.tadu.com/book/*/toc/
// @include        *://www.50zw.com/book_*/*.html
// @include        *://www.wenxue8.org/html/*/*/*.html
// @match          *://www.bixia.org/book/*/*.html
// @match          *://www.67book.net/book/*/*.html
// @match          *://www.50zw.org/book/*/*.html
// @match          *://www.luoqiuzw.com/book/*/*.html
// @match          *://www.xiaoshuo.cc/*/*.html
// @match          *://www.tyue.net/*/*.html
// @match          *://www.biduoxs.com/biquge/*/*.html
// @match          *://www.aixswx.com/xs/*/*/*.html
// @match          *://www.wucuoxs.com/*/*.html
// @match          *://www.7017k.com/*/*.html
// @match          *://www.piaotianwenxue.com/book/*/*/*.html
// @match          *://www.txtshuku.org/so/*/*.html
// @match          *://www.wcxsw.org/*/*.html
// @match          *://www.min-yuan.com/book/*/*.html
// @match          *://www.tatajk.net/book/*/*.html
// @match          *://www.147xs.org/book/*/*.html
// @match          *://www.biqugeso.org/biquge_*/*.html


// 其它网站
// @include        *://book.sfacg.com/Novel/*/*/*/
// @include        *://www.zhaoshuyuan.com/*/*/*.html*
// @include        *://book.kanunu.org/*/*/*.html
// @include        *://www.kanunu8.com/book*/*.html
// @include        *://www.epzww.com/book/*/*
// @include        *://www.biqudu.com/*/*.html
// @include        *://www.qududu.com/book/*/*/*.html
// @include        *://b.faloo.com/p/*/*.html
// @include        *://b.faloo.com/*_*.html
// @include        *://www.my285.com/*/*/*/*.htm
// @include        *://www.hjwzw.com/Book/Read/*,*
// @include        *://www.hjwzw.com/Book/Read/*_*
// @include        *://www.69shu.top/txt/*/*
// @include        *://www.biquge5200.cc/*/*.html
// @include        *://read.qidian.com/chapter/*
// @include        *://www.piaotia.com/html/*/*/*.html
// @include        *://www.miaobige.com/*/*/*.html
// @include        *://www.shuhai.com/read/*/*.html
// @include        *://www.23qb.com/book/*/*.html
// @include        *://www.lucifer-club.com/chapter-*-*.html
// @include        *://www.quanben.io/*/*/*.html
// @include        *://www.b5200.org/*/*.html
// @include        *://www.b5200.net/*/*.html
// @include        *://novel.tingroom.com/*/*/*.html
// @include        *://www.ciweimao.com/chapter/*
// @include        *://m.zwduxs.com/*_*/*.html
// @include        *://www.ranwen.la/files/article/*/*/*.html
// @include        *://www.3xs.cc/*/*.html
// @include        *://www.nuanyuehanxing.cc/*/*/*.html
// @include        *://www.gongzicp.com/read-*.html
// @include        *://www.xs321.net/book/*/*/*.html
// @include        *://www.hetushu.com/book/*/*.html
// @include        *://www.zhaishuyuan.org/book/*/*.html
// @include        *://www.00ksw.com/html/*/*/*.html
// @include        *://www.99bxwx.com/b/*/*.html
// @match          *://www.81zw.com/book/*/*.html
// @match          *://www.biqu5200.net/*/*.html
// @match          *://www.biqusa.com/*/*.html
// @match          *://www.biququ.com/html/*/*.html
// @match          *://www.ddxs.com/*/*.html
// @match          *://www.xn--fiq228cu93a4kh.com/Html/*/*.html
// @match          *://www.555x.org/read/*/*.html
// @match          *://www.soxscc.net/*/*.html
// @match          *://www.linovelib.com/novel/*/*.html
// @match          *://www.uuks.org/b/*/*.html
// @match          *://www.230book.net/book/*/*.html
// @match          *://www.exiaoshuo.com/*/*/
// @match          *://www.877zw.com/*/*.html
// @match          *://www.zhuixsw.com/*/*.html
// @match          *://www.ddxs.com/*/*.html
// @match          *://www.bqxs520.com/*/*.html
// @match          *://www.bidige.com/book/*/*.html
// @match          *://www.yushubo.com/read_*.html
// @match          *://www.bqwxg8.com/wenzhang/*/*/*.html
// @match          *://www.zpxsw.com/*/*.html
// @match          *://www.xbiqukan.com/book/*/*.html
// @match          *://www.51kanshu.cc/book/*/*.html
// @match          *://www.mibaoge.com/*/*.html
// @match          *://www.asxs.com/view/*/*.html
// @match          *://www.xinshuw.cc/*/*.html
// @match          *://www.yodu.org/book/*/*.html
// @match          *://www.fantuantanshu.com/*/*.html
// @match          *://www.tsxsw.net/html/*/*/*.html
// @match          *://www.xiaoshuting.org/book/*/*.html
// @match          *://www.xiaoshuting.la/*/*/*.html
// @match          *://www.xiaoshuting.cc/xiaoshuo/*/*/*.html
// @match          *://www.xiaoshuting.info/read/*/*/*.html
// @match          *://www.xiaoshutingapp.com/html/*/*.html
// @match          *://www.fantuankanshu.com/html/*/*/*.html
// @match          *://www.loubiqu.net/html/*/*.html
// @match          *://www.1200ksw.net/html/*/*/*.html
// @match          *://www.ranwena.net/files/article/*/*/*.html
// @match          *://www.biququ.info/html/*/*.html
// @match          *://www.fqxsw.org/html/*/*.html
// @match          *://www.cxzww.com/read/*/*/*.html
// @match          *://www.5ebook.net/book/*/*/*.html
// @match          *://www.yyxs.la/html/*/*/*.html
// @match          *://www.slkslk.com/*/*/*/*.html
// @match          *://www.siluke.com/*/*/*/*.html
// @match          *://www.bqgxsydw.com/html/*/*/*.html
// @match          *://www.lingdiankanshu.com/html/*/*/*.html
// @match          *://www.beqege.cc/*/*.html
// @match          *://www.yqxsw.org/html/*/*/*.html
// @match          *://www.2kxiaoshuo.com/xiaoshuo/*/*/*.html
// @match          *://www.2kxs.la/xiaoshuo/*/*/*.html
// @match          *://www.31xs.org/*/*/*.html
// @match          *://www.31xs.net/*/*/*.html
// @match          *://www.01xs.com/xiaoshuo/*/*.html
// @match          *://www.biquge.name/html/*/*/*.html
// @match          *://www.yawenba.net/book/*/*.html
// @match          *://www.aiyueshuxiang.com/html/*/*.html
// @match          *://www.zhenhunxiaoshuo.com/*.html
// @match          *://www.xiyuwx.com/*/*.html
// @match          *://www.waptxt.com/*/*.html
// @match          *://www.5xw.net/*/*/*.html
// @match          *://www.5ycn.com/*/*/*.html
// @match          *://www.67shu.net/book/*/*.html
// @match          *://zerifeisheng.com/book/*/*.html
// @match          *://quanxiaoshuo.com/*/*/
// @match          *://www.bg3.co/novel/pagea/*.html
// @match          *://cn.bg3.co/novel/pagea/*.html
// @match          *://tw.bg3.co/novel/pagea/*.html
// @match          *://www.wa01.com/novel/pagea/*.html
// @match          *://cn.wa01.com/novel/pagea/*.html
// @match          *://tw.wa01.com/novel/pagea/*.html
// @match          *://www.babahome.net/*/*.html
// @match          *://wufangdao.com/html/*/*/*.html
// @match          *://www.jinghuashuge.cc/id/*/*.html
// @match          *://www.qbiqus.com/*/*.html
// @match          *://www.123dua.com/dudu-*/*/*.html
// @match          *://www.17yue.com/*/*.html
// @match          *://www.nuoqiu.com/*/*.html
// @match          *://www.yawen8.com/*/*/*.html
// @match          *://www.bookxuan.org/book/*/*/*.html
// @match          *://www.shenmaxiaoshuo.com/book/*/*.html
// @match          *://www.16kbook.org/book/*/*.html
// @match          *://www.1kanshu.com/html/*/*.html
// @match          *://www.dawenxue.net/*/*.html
// @match          *://www.tbxsww.com/html/*/*/*.html
// @match          *://www.33yq.org/read/*/*.shtml
// @match          *://www.3uxiaoshuo.com/xiaoshuo/*/*.html
// @match          *://www.zrfsxs.com/xiaoshuo/*/*.html
// @match          *://www.31xs.com/*/*/*.html
// @match          *://www.70sw.net/read/*/*/*.html
// @match          *://www.qisxs.com/*/*.html
// @match          *://www.zhswx.com/zhsread/*.html
// @match          *://www.zfxwx.com/read/*/*.html
// @match          *://www.622zw.com/books/*/*.html
// @match          *://www.deqixs.com/xiaoshuo/*/*.html
// @match          *://www.fkxs.net/*/*.html
// @match          *://www.09k.net/kkb/*/*.html
// @match          *://www.yulusy.com/yulus/*/*.html
// @match          *://sangtacviet.vip/truyen/*/1/*/*/
// @match          *://www.shoujix.com/*.html
// @match          *://www.twking.cc/*_*/*.html
// @match          *://www.bilinovel.com/novel/*/*.html
// @match          *://tw.bilinovel.com/novel/*/*.html
// @match          *://tw.linovelib.com/novel/*/*.html
// @match          *://www.wenku8.net/novel/*/*/*.htm
// @match          *://www.uuread.tw/chapter/*/*.html
// @match          *://69shux.com/txt/*/*
// @match          *://www.biquxs.com/book/*/*.html
// @match          *://www.dbxsc.com/book/*/*.html
// @match          *://www.weifengxs.com/chapter/*/*.html
// @match          *://m.wfxs.tw/xiaoshuo/*/*/
// @match          *://www.wfxs.tw/xiaoshuo/*/*/
// @match          *://feibzw.com/Html/*/*.html
// @match          *://www.xsbiquge.la/book/*/*.html
// @match          *://www.bqgege.com/reader/*/*
// @match          *://www.dxmwx.org/read/*_*.html
// @match          *://ixdzs8.com/read/*/*.html
// @match          *://69shuba.cx/txt/*/*
// @match          *://twkan.com/txt/*/*
// @match          *://101kks.com/txt/*/*.html

// legado-webui
// @match          *://localhost:5000/bookshelf/*/*/

// 移动版
// @include        *://m.jjwxc.net/book2/*/*
// @include        *://m.jjwxc.com/book2/*/*
// @include        *://wap.jjwxc.net/book2/*/*
// @include        *://wap.jjwxc.com/book2/*/*
// @include        *://wap.jjwxc.com/vip/*/*?ctime=*
// @include        *://wap.jjwxc.com/vip/*/*
// @include        *://wap.jjwxc.net/vip/*/*
// @include        *://m.jjwxc.net/vip/*/*
// @include        *://m.jjwxc.com/vip/*/*
// @match          *://m.xindingdianxsw.com/*/*/*.html
// @match          *://m.123dua.com/dudu-*/*/*.html
// @match          *://m.biquxs.com/book/*/*.html
// @match          *://m.yulusy.com/yulus/*/*.html
// @match          *://m.xianqihaotianmi.org/*/*.html

// @exclude        */List.htm
// @exclude        */List.html
// @exclude        */List.shtml
// @exclude        */index.htm
// @exclude        */index.html
// @exclude        */index.shtml
// @exclude        */Default.htm
// @exclude        */Default.html
// @exclude        */Default.shtml

// @run-at         document-body
// ==/UserScript==
